Fix for crash when forgetting a required field.
Problem was:
```
root@server:~# /usr/share/pdagent-integrations/bin/pd-nagios -n service -k my_secret -t PROBLEM
Traceback (most recent call last):
  File "/usr/share/pdagent-integrations/bin/pd-nagios", line 188, in <module>
    main()
  File "/usr/share/pdagent-integrations/bin/pd-nagios", line 128, in main
    incident_key = event.enqueue()
  File "/usr/share/pdagent-integrations/bin/pd-nagios", line 58, in enqueue
    self._check_required_fields()
  File "/usr/share/pdagent-integrations/bin/pd-nagios", line 102, in _check_required_fields
    ", ".join(self._required_fields())
AttributeError: NagiosEvent instance has no attribute '_required_fields'
```